In [10]:
import os, sys, datetime, logging
import numpy as np
import pandas as pd
import json 
from datetime import datetime

if '../' not in sys.path:
    sys.path.append('../')
    
import import_ipynb
from util.s3_method import * 
from util.time_method import *
from util.plot_method import easy_plot,timeline_sample_kv, get_plot_diff_data
from util.hedge_log import initlog
from util.recover_depth import recoveryDepth
from util.statistic_method_v2 import describe_series
from util.load_s3_data import *

In [11]:
from convert_depth_format import *

In [12]:
exchange = 'binance'
symbol="btc_usdt"

In [17]:
i = 30
begin_time = datetime.datetime(2024, 1, i, 1, tzinfo=TZ_8)
end_time = datetime.datetime(2024, 1, i+1, 1,tzinfo=TZ_8)

In [18]:
# Data Download
depth = LoadS3Data.get_cex_depth(begin_time, end_time, exchange, symbol)

begin to recover depth at date 2024013001: 2024-03-11 07:08:59.304040
finish depth recovery at 2024-03-11 07:09:09.575483
begin to recover depth at date 2024013002: 2024-03-11 07:09:09.724266
finish depth recovery at 2024-03-11 07:09:17.132625
begin to recover depth at date 2024013003: 2024-03-11 07:09:17.241703
finish depth recovery at 2024-03-11 07:09:23.574923
begin to recover depth at date 2024013004: 2024-03-11 07:09:23.693758
finish depth recovery at 2024-03-11 07:09:29.778978
begin to recover depth at date 2024013005: 2024-03-11 07:09:29.889589
finish depth recovery at 2024-03-11 07:09:35.223744
begin to recover depth at date 2024013006: 2024-03-11 07:09:35.328166
finish depth recovery at 2024-03-11 07:09:39.988320
begin to recover depth at date 2024013007: 2024-03-11 07:09:40.068603
finish depth recovery at 2024-03-11 07:09:44.833236
begin to recover depth at date 2024013008: 2024-03-11 07:09:44.923114
finish depth recovery at 2024-03-11 07:09:50.495758
begin to recover depth at date 2024013009: 2024-03-11 07:09:50.588707
finish depth recovery at 2024-03-11 07:09:58.207325
begin to recover depth at date 2024013010: 2024-03-11 07:09:58.347717
finish depth recovery at 2024-03-11 07:10:06.541267
begin to recover depth at date 2024013011: 2024-03-11 07:10:06.688128
finish depth recovery at 2024-03-11 07:10:12.486890
begin to recover depth at date 2024013012: 2024-03-11 07:10:12.610377
finish depth recovery at 2024-03-11 07:10:17.015561
begin to recover depth at date 2024013013: 2024-03-11 07:10:17.105594
finish depth recovery at 2024-03-11 07:10:22.463971
begin to recover depth at date 2024013014: 2024-03-11 07:10:22.548202
finish depth recovery at 2024-03-11 07:10:26.926372
begin to recover depth at date 2024013015: 2024-03-11 07:10:27.009573
finish depth recovery at 2024-03-11 07:10:31.468382
begin to recover depth at date 2024013016: 2024-03-11 07:10:31.554624
finish depth recovery at 2024-03-11 07:10:38.145611
begin to recover depth at date 2024013017: 2024-03-11 07:10:38.242833
finish depth recovery at 2024-03-11 07:10:42.508090
begin to recover depth at date 2024013018: 2024-03-11 07:10:42.593061
finish depth recovery at 2024-03-11 07:10:46.984992
begin to recover depth at date 2024013019: 2024-03-11 07:10:47.069607
finish depth recovery at 2024-03-11 07:10:52.342641
begin to recover depth at date 2024013020: 2024-03-11 07:10:52.445738
finish depth recovery at 2024-03-11 07:11:05.753985
begin to recover depth at date 2024013021: 2024-03-11 07:11:05.954239
finish depth recovery at 2024-03-11 07:11:14.201677
begin to recover depth at date 2024013022: 2024-03-11 07:11:14.355939
finish depth recovery at 2024-03-11 07:11:22.673593
begin to recover depth at date 2024013023: 2024-03-11 07:11:22.851689
finish depth recovery at 2024-03-11 07:11:31.931574
begin to recover depth at date 2024013100: 2024-03-11 07:11:32.128821
finish depth recovery at 2024-03-11 07:11:39.556770
begin to recover depth at date 2024013101: 2024-03-11 07:11:39.728768
finish depth recovery at 2024-03-11 07:11:46.478209

In [20]:
# Data Saving
json_path = "data/btc_usdt/depth_202401" + str(i) + ".json"
with open(json_path, "w") as f:
    json.dump(depth, f)

In [6]:
# Data Loading
with open(json_path, "r") as f:
    depth = json.load(f)

In [21]:
depth_df = convert_depth_format3(depth)

In [22]:
pq_path = "data/btc_usdt/depth_202401" + str(i) + ".parquet"
depth_df.to_parquet(pq_path)

In [23]:
depth_df.head()

,time,bid1,bid_qty1,bid2,bid_qty2,bid3,bid_qty3,bid4,bid_qty4,bid5,bid_qty5,ask1,ask_qty1,ask2,ask_qty2,ask3,ask_qty3,ask4,ask_qty4,ask5,ask_qty5
time,,,,,,,,,,,,,,,,,,,,,
2024-01-29 17:01:01.994,1706547661994,43277.74,4.64911,43277.55,0.23445,43277.54,0.13067,43277.51,0.07227,43277.27,0.00021,43277.74,4.64911,43277.55,0.23445,43277.54,0.13067,43277.51,0.07227,43277.27,0.00021
2024-01-29 17:01:02.094,1706547662094,43277.74,2.99577,43277.55,0.23445,43277.54,0.13067,43277.51,0.07227,43277.27,0.00021,43277.74,2.99577,43277.55,0.23445,43277.54,0.13067,43277.51,0.07227,43277.27,0.00021
2024-01-29 17:01:02.194,1706547662194,43277.74,4.12732,43277.55,0.23445,43277.54,0.13067,43277.51,0.07227,43277.27,0.00021,43277.74,4.12732,43277.55,0.23445,43277.54,0.13067,43277.51,0.07227,43277.27,0.00021
2024-01-29 17:01:02.294,1706547662294,43277.74,4.12732,43277.63,0.00409,43277.54,0.13067,43277.51,0.07227,43277.27,0.00021,43277.74,4.12732,43277.63,0.00409,43277.54,0.13067,43277.51,0.07227,43277.27,0.00021
2024-01-29 17:01:02.394,1706547662394,43277.74,4.12732,43277.63,0.00409,43277.54,0.13067,43277.51,0.07227,43277.27,0.00021,43277.74,4.12732,43277.63,0.00409,43277.54,0.13067,43277.51,0.07227,43277.27,0.00021